In [107]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [108]:
df = pd.read_csv("data/dataset/Pakistan Largest Ecommerce Dataset.csv")
df.head()

C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\4065062114.py:1: DtypeWarning: Columns (1,2,3,7,8,9,11,12,13,14,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/dataset/Pakistan Largest Ecommerce Dataset.csv")

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,NaN,NaN,NaN,NaN,NaN
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,NaN,NaN,NaN,NaN,NaN
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,NaN,NaN,NaN,NaN,NaN
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,NaN,NaN,NaN,NaN,NaN
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,NaN,NaN,NaN,NaN,NaN

In [109]:
df.shape

(1048575, 26)

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  float64
 1   status                 584509 non-null  object
 2   created_at             584524 non-null  object
 3   sku                    584504 non-null  object
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  float64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  object
 9   sales_commission_code  447346 non-null  object
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  object
 12  Working Date           584524 non-null  object
 13  BI Status              584524 non-null  object
 14   MV                    584524 non-null  object
 15  Year                   584524 non-null  float64
 16  Month                  584524 non-null  float64
 17  Customer Since         584513 non-null  object
 18  M-Y                    584524 non-null  object
 19  FY                     584524 non-null  object
 20  Customer ID            584513 non-null  float64
 21  Unnamed: 21            0 non-null       float64
 22  Unnamed: 22            0 non-null       float64
 23  Unnamed: 23            0 non-null       float64
 24  Unnamed: 24            0 non-null       float64
 25  Unnamed: 25            0 non-null       float64
dtypes: float64(13), object(13)
memory usage: 208.0+ MB

In [111]:
df.describe()

,item_id,price,qty_ordered,grand_total,discount_amount,Year,Month,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,584524.000000,5.845240e+05,584524.000000,5.845240e+05,584524.000000,584524.000000,584524.000000,584513.000000,0.0,0.0,0.0,0.0,0.0
mean,565667.074218,6.348748e+03,1.296388,8.530619e+03,499.492775,2017.044115,7.167654,45790.511965,NaN,NaN,NaN,NaN,NaN
std,200121.173648,1.494927e+04,3.996061,6.132081e+04,1506.943046,0.707355,3.486305,34414.962389,NaN,NaN,NaN,NaN,NaN
min,211131.000000,0.000000e+00,1.000000,-1.594000e+03,-599.500000,2016.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
25%,395000.750000,3.600000e+02,1.000000,9.450000e+02,0.000000,2017.000000,4.000000,13516.000000,NaN,NaN,NaN,NaN,NaN
50%,568424.500000,8.990000e+02,1.000000,1.960400e+03,0.000000,2017.000000,7.000000,42856.000000,NaN,NaN,NaN,NaN,NaN
75%,739106.250000,4.070000e+03,1.000000,6.999000e+03,160.500000,2018.000000,11.000000,73536.000000,NaN,NaN,NaN,NaN,NaN
max,905208.000000,1.012626e+06,1000.000000,1.788800e+07,90300.000000,2018.000000,12.000000,115326.000000,NaN,NaN,NaN,NaN,NaN

In [112]:
df.isnull().sum()

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [113]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', ' MV ', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [114]:
df.isnull().sum()

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [115]:
df = df.dropna(axis=1, how='all')

In [116]:
df = df.drop_duplicates()

In [117]:
df.isnull().sum()

item_id                       1
status                       16
created_at                    1
sku                          21
price                         1
qty_ordered                   1
grand_total                   1
increment_id                  1
category_name_1             165
sales_commission_code    137179
discount_amount               1
payment_method                1
Working Date                  1
BI Status                     1
 MV                           1
Year                          1
Month                         1
Customer Since               12
M-Y                           1
FY                            1
Customer ID                  12
dtype: int64

In [118]:
df.duplicated().sum()

np.int64(0)

In [119]:
df.dtypes

item_id                  float64
status                    object
created_at                object
sku                       object
price                    float64
qty_ordered              float64
grand_total              float64
increment_id              object
category_name_1           object
sales_commission_code     object
discount_amount          float64
payment_method            object
Working Date              object
BI Status                 object
 MV                       object
Year                     float64
Month                    float64
Customer Since            object
M-Y                       object
FY                        object
Customer ID              float64
dtype: object

In [120]:
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
df['Working Date'] = pd.to_datetime(df['Working Date'], errors='coerce')
df['Customer Since'] = pd.to_datetime(df['Customer Since'], errors='coerce')
df['M-Y'] = pd.to_datetime(df['M-Y'], errors='coerce')

C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\187682837.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['M-Y'] = pd.to_datetime(df['M-Y'], errors='coerce')

In [121]:
df.dtypes

item_id                         float64
status                           object
created_at               datetime64[ns]
sku                              object
price                           float64
qty_ordered                     float64
grand_total                     float64
increment_id                     object
category_name_1                  object
sales_commission_code            object
discount_amount                 float64
payment_method                   object
Working Date             datetime64[ns]
BI Status                        object
 MV                              object
Year                            float64
Month                           float64
Customer Since           datetime64[ns]
M-Y                      datetime64[ns]
FY                               object
Customer ID                     float64
dtype: object

In [122]:
df.describe()

,item_id,created_at,price,qty_ordered,grand_total,discount_amount,Working Date,Year,Month,Customer Since,M-Y,Customer ID
count,584524.000000,584524,5.845240e+05,584524.000000,5.845240e+05,584524.000000,584524,584524.000000,584524.000000,584513,584524,584513.000000
mean,565667.074218,2017-08-08 11:42:53.589450752,6.348748e+03,1.296388,8.530619e+03,499.492775,2017-08-08 11:42:53.589450752,2017.044115,7.167654,2017-04-24 18:56:21.904593664,2017-07-22 22:17:21.536703488,45790.511965
min,211131.000000,2016-07-01 00:00:00,0.000000e+00,1.000000,-1.594000e+03,-599.500000,2016-07-01 00:00:00,2016.000000,1.000000,2016-07-01 00:00:00,2016-07-01 00:00:00,1.000000
25%,395000.750000,2017-01-29 00:00:00,3.600000e+02,1.000000,9.450000e+02,0.000000,2017-01-29 00:00:00,2017.000000,4.000000,2016-11-01 00:00:00,2017-01-01 00:00:00,13516.000000
50%,568424.500000,2017-08-17 00:00:00,8.990000e+02,1.000000,1.960400e+03,0.000000,2017-08-17 00:00:00,2017.000000,7.000000,2017-04-01 00:00:00,2017-08-01 00:00:00,42856.000000
75%,739106.250000,2018-02-03 00:00:00,4.070000e+03,1.000000,6.999000e+03,160.500000,2018-02-03 00:00:00,2018.000000,11.000000,2017-11-01 00:00:00,2018-02-01 00:00:00,73536.000000
max,905208.000000,2018-08-28 00:00:00,1.012626e+06,1000.000000,1.788800e+07,90300.000000,2018-08-28 00:00:00,2018.000000,12.000000,2018-08-01 00:00:00,2018-08-01 00:00:00,115326.000000
std,200121.173648,NaN,1.494927e+04,3.996061,6.132081e+04,1506.943046,NaN,0.707355,3.486305,NaN,NaN,34414.962389

In [123]:
numeric_cols = df.select_dtypes(include=[np.number]).columns

In [124]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

In [125]:
df.shape

(299613, 21)

In [126]:
col = 'price'
print("Before:", df[col].describe())
print("After:", df[col].describe())

Before: count    299613.000000
mean        867.363187
std        1007.661994
min           0.000000
25%         279.000000
50%         540.000000
75%        1000.000000
max        9599.000000
Name: price, dtype: float64
After: count    299613.000000
mean        867.363187
std        1007.661994
min           0.000000
25%         279.000000
50%         540.000000
75%        1000.000000
max        9599.000000
Name: price, dtype: float64

In [127]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [128]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

In [129]:
scaler_standard = StandardScaler()
df_standardized = df.copy()
df_standardized[numeric_cols] = scaler_standard.fit_transform(df[numeric_cols])

In [130]:
scaler_normal = MinMaxScaler()
df_normalized = df.copy()
df_normalized[numeric_cols] = scaler_normal.fit_transform(df[numeric_cols])

In [131]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [132]:
df['status'] = df['status'].str.strip().str.lower()
df['payment_method'] = df['payment_method'].str.strip().str.lower()
df['category_name_1'] = df['category_name_1'].str.strip().str.lower()
df['sku'] = df['sku'].str.strip().str.lower()
df['sales_commission_code'] = df['sales_commission_code'].str.strip().str.lower()
df['bi_status'] = df['bi_status'].str.strip().str.lower()

In [133]:
df['category_name_1'].value_counts()

category_name_1
men's fashion         74097
women's fashion       37422
mobiles & tablets     30854
beauty & grooming     29099
soghaat               25717
superstore            20190
home & living         17649
appliances            14672
health & sports       12726
kids & baby           12315
others                 7137
computing              6418
\n                     4140
entertainment          3093
school & education     2691
books                  1341
Name: count, dtype: int64

In [134]:
df['category_name_1'] = df['category_name_1'].replace('\n', 'others')

In [135]:
df['category_name_1'] = df['category_name_1'].replace('others', 'unknown')

In [136]:
df['category_name_1'].value_counts()

category_name_1
men's fashion         74097
women's fashion       37422
mobiles & tablets     30854
beauty & grooming     29099
soghaat               25717
superstore            20190
home & living         17649
appliances            14672
health & sports       12726
kids & baby           12315
unknown                7137
computing              6418
\n                     4140
entertainment          3093
school & education     2691
books                  1341
Name: count, dtype: int64

In [137]:
df['payment_method'].value_counts()

payment_method
cod                  201066
payaxis               27820
easypay               24104
jazzwallet            16746
bankalfalah            6472
customercredit         5724
easypay_ma             4980
easypay_voucher        4894
jazzvoucher            4727
apg                     837
cashatdoorstep          671
mcblite                 550
ublcreditcard           367
internetbanking         271
mygateway               241
productcredit           112
marketingexpense         30
financesettlement         1
Name: count, dtype: int64

In [138]:
df['payment_method'] = df['payment_method'].replace({
    'cashatdoorstep': 'cod',
    'easypay_ma': 'easypay',
    'easypay_voucher': 'easypay',
    'jazzvoucher': 'jazzwallet',
    'bankalfalah': 'bank_payment',
    'ublcreditcard': 'bank_payment',
    'internetbanking': 'bank_payment',
    'mygateway': 'bank_payment',
    'other': 'unknown'
})

In [139]:
df['payment_method'].value_counts()

payment_method
cod                  201737
easypay               33978
payaxis               27820
jazzwallet            21473
bank_payment           7351
customercredit         5724
apg                     837
mcblite                 550
productcredit           112
marketingexpense         30
financesettlement         1
Name: count, dtype: int64

In [140]:
df['status'].value_counts()

status
complete          141356
canceled           69446
received           41069
order_refunded     39719
refund              5165
cod                 2059
paid                 437
closed               300
processing            27
pending                8
holded                 6
pending_paypal         6
exchange               4
\n                     2
Name: count, dtype: int64

In [141]:
df['status'] = df['status'].replace({
    'refund': 'order_refunded',
    'pending_paypal': 'pending',
    'cod': 'complete',
    'paid': 'complete',
    'closed': 'complete',
    'processing': 'pending',
    'holded': 'pending',
    'exchange': 'order_refunded',
    'others': 'unknown'
})

In [142]:
df['status'].value_counts()

status
complete          144152
canceled           69446
order_refunded     44888
received           41069
pending               47
\n                     2
Name: count, dtype: int64

In [143]:
df['sales_commission_code'].value_counts()

sales_commission_code
\n               191583
c-lhc-30667        1324
c-lhw-50074        1246
r-guj-51944         949
c-mux-33202         834
                  ...
51597                 1
grs-4090975-1         1
125                   1
5iggtu                1
865116                1
Name: count, Length: 4960, dtype: int64

In [144]:
df['sales_commission_code'] = df['sales_commission_code'].replace('\\N', 'unknown')

In [145]:
df['sales_commission_code'].value_counts()

sales_commission_code
\n               191583
c-lhc-30667        1324
c-lhw-50074        1246
r-guj-51944         949
c-mux-33202         834
                  ...
51597                 1
grs-4090975-1         1
125                   1
5iggtu                1
865116                1
Name: count, Length: 4960, dtype: int64

In [146]:
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.dtypes)
print(df['status'].unique())
print(df['payment_method'].unique())
print(df['category_name_1'].unique())
print((df['price'] < 0).sum())
print((df['qty_ordered'] < 0).sum())
print((df['grand_total'] < 0).sum())

item_id                      0
status                       9
created_at                   0
sku                         13
price                        0
qty_ordered                  0
grand_total                  0
increment_id                 0
category_name_1             52
sales_commission_code    54784
discount_amount              0
payment_method               0
working_date                 0
bi_status                    0
mv                           0
year                         0
month                        0
customer_since               0
m-y                          0
fy                           0
customer_id                  0
dtype: int64
0
item_id                         float64
status                           object
created_at               datetime64[ns]
sku                              object
price                           float64
qty_ordered                     float64
grand_total                     float64
increment_id                     object
category_name_1                  object
sales_commission_code            object
discount_amount                 float64
payment_method                   object
working_date             datetime64[ns]
bi_status                        object
mv                               object
year                            float64
month                           float64
customer_since           datetime64[ns]
m-y                      datetime64[ns]
fy                               object
customer_id                     float64
dtype: object
['complete' 'canceled' 'received' 'order_refunded' 'pending' '\\n' nan]
['cod' 'bank_payment' 'customercredit' 'mcblite' 'marketingexpense'
 'productcredit' 'financesettlement' 'payaxis' 'jazzwallet' 'easypay'
 'apg']
["women's fashion" 'beauty & grooming' 'soghaat' 'appliances'
 'home & living' "men's fashion" 'kids & baby' '\\n' 'unknown'
 'mobiles & tablets' 'computing' 'superstore' 'health & sports'
 'entertainment' 'books' 'school & education' nan]
0
0
15

In [147]:
df['status'].fillna('unknown', inplace=True)
df['sku'].fillna('unknown', inplace=True)
df['category_name_1'].fillna('others', inplace=True)
df['sales_commission_code'].fillna('unknown', inplace=True)

C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\953510532.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['status'].fillna('unknown', inplace=True)
C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\953510532.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sku'].fillna('unknown', inplace=True)
C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\953510532.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category_name_1'].fillna('others', inplace=True)
C:\Users\elsay\AppData\Local\Temp\ipykernel_5080\953510532.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sales_commission_code'].fillna('unknown', inplace=True)

In [148]:
print(df.isnull().sum())

item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
working_date             0
bi_status                0
mv                       0
year                     0
month                    0
customer_since           0
m-y                      0
fy                       0
customer_id              0
dtype: int64